export const notificationTypes = {
  ENVELOPE_CREATED: 'ENVELOPE_CREATED',
  SIGNER_SIGNED: 'SIGNER_SIGNED',
  ENVELOPE_COMPLETED: 'ENVELOPE_COMPLETED',
  ENVELOPE_DECLINED: 'ENVELOPE_DECLINED',
  ENVELOPE_CANCELLED: 'ENVELOPE_CANCELLED',
  FORM_ASSIGNED: 'FORM_ASSIGNED',
  FORM_COMPLETED: 'FORM_COMPLETED',
  FORM_CANCELLED: 'FORM_CANCELLED',
};
