export const initialFormFields = [
  {
    input: false,
    components: [
      {
        input: true,
        conditional: {
          show: null,
          eq: '',
          when: null,
        },
        tableView: true,
        disabled: false,
        label: 'First Name',
        id: 'ebrrfme',
        type: 'textfield',
        key: 'firstName',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          unique: false,
          minLength: '',
          multiple: false,
          pattern: '',
          required: true,
          maxLength: '',
        },
        placeholder: '',
        prefix: '',
        customClass: '',
        suffix: '',
        multiple: false,
        defaultValue: null,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        refreshOn: '',
        redrawOn: '',
        modalEdit: false,
        dataGridLabel: false,
        labelPosition: 'top',
        description: '',
        errorLabel: '',
        tooltip: '',
        hideLabel: false,
        tabindex: '',
        autofocus: false,
        dbIndex: false,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        widget: {
          type: 'input',
        },
        attributes: {},
        validateOn: 'change',
        overlay: {
          style: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        allowCalculateOverride: false,
        encrypted: false,
        showCharCount: false,
        showWordCount: false,
        properties: {},
        allowMultipleMasks: false,
        mask: false,
        inputType: 'text',
        inputFormat: 'plain',
        inputMask: '',
        spellcheck: true,
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        input: true,
        conditional: {
          show: null,
          json: '',
          eq: '',
          when: null,
        },
        tableView: true,
        disabled: false,
        label: 'Middle Initial',
        id: 'eaalwh',
        type: 'textfield',
        key: 'middleInitial',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          minLength: '',
          unique: false,
          pattern: '',
          multiple: false,
          customMessage: '',
          json: '',
          required: false,
          maxLength: '',
        },
        customConditional: '',
        placeholder: '',
        prefix: '',
        customClass: '',
        suffix: '',
        multiple: false,
        defaultValue: null,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        refreshOn: '',
        redrawOn: '',
        modalEdit: false,
        dataGridLabel: false,
        labelPosition: 'top',
        description: '',
        errorLabel: '',
        tooltip: '',
        hideLabel: false,
        tabindex: '',
        autofocus: false,
        dbIndex: false,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        widget: {
          type: 'input',
        },
        attributes: {},
        validateOn: 'change',
        overlay: {
          style: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        allowCalculateOverride: false,
        encrypted: false,
        showCharCount: false,
        showWordCount: false,
        properties: {},
        allowMultipleMasks: false,
        mask: false,
        inputType: 'text',
        inputFormat: 'plain',
        inputMask: '',
        spellcheck: true,
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        input: true,
        conditional: {
          show: null,
          json: '',
          eq: '',
          when: null,
        },
        tableView: true,
        disabled: false,
        label: 'Last Name',
        id: 'efnmjqs',
        type: 'textfield',
        key: 'lastName',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          minLength: '',
          unique: false,
          pattern: '',
          multiple: false,
          customMessage: '',
          json: '',
          required: true,
          maxLength: '',
        },
        customConditional: '',
        placeholder: '',
        prefix: '',
        customClass: '',
        suffix: '',
        multiple: false,
        defaultValue: null,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        refreshOn: '',
        redrawOn: '',
        modalEdit: false,
        dataGridLabel: false,
        labelPosition: 'top',
        description: '',
        errorLabel: '',
        tooltip: '',
        hideLabel: false,
        tabindex: '',
        autofocus: false,
        dbIndex: false,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        widget: {
          type: 'input',
        },
        attributes: {},
        validateOn: 'change',
        overlay: {
          style: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        allowCalculateOverride: false,
        encrypted: false,
        showCharCount: false,
        showWordCount: false,
        properties: {},
        allowMultipleMasks: false,
        mask: false,
        inputType: 'text',
        inputFormat: 'plain',
        inputMask: '',
        spellcheck: true,
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        input: true,
        conditional: {
          show: null,
          json: '',
          eq: '',
          when: null,
        },
        tableView: true,
        disabled: false,
        label: 'Email',
        id: 'enxiip',
        type: 'email',
        key: 'email',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          minLength: '',
          unique: false,
          pattern: '',
          multiple: false,
          customMessage: '',
          json: '',
          required: true,
          maxLength: '',
        },
        customConditional: '',
        placeholder: '',
        prefix: '',
        customClass: '',
        suffix: '',
        multiple: false,
        defaultValue: null,
        protected: false,
        unique: false,
        persistent: true,
        hidden: false,
        clearOnHide: true,
        refreshOn: '',
        redrawOn: '',
        modalEdit: false,
        dataGridLabel: false,
        labelPosition: 'top',
        description: '',
        errorLabel: '',
        tooltip: '',
        hideLabel: false,
        tabindex: '',
        autofocus: false,
        dbIndex: false,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        widget: {
          type: 'input',
        },
        attributes: {},
        validateOn: 'change',
        overlay: {
          style: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        allowCalculateOverride: false,
        encrypted: false,
        showCharCount: false,
        showWordCount: false,
        properties: {},
        allowMultipleMasks: false,
        mask: false,
        inputType: 'email',
        inputFormat: 'plain',
        inputMask: '',
        spellcheck: true,
        kickbox: {
          enabled: false,
        },
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        label: 'Phone Number',
        labelPosition: 'top',
        placeholder: '',
        description: '',
        tooltip: '',
        prefix: '',
        suffix: '',
        widget: {
          type: 'input',
        },
        inputMask: '',
        displayMask: '(999) 999-9999',
        applyMaskOn: 'change',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        mask: false,
        autofocus: false,
        spellcheck: false,
        disabled: false,
        tableView: false,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        truncateMultipleSpaces: false,
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: true,
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
          minLength: '',
          maxLength: '',
          pattern: '',
        },
        unique: false,
        validateWhenHidden: false,
        errorLabel: '',
        errors: '',
        key: 'phoneNumber',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'phoneNumber',
        dataGridLabel: false,
        input: true,
        refreshOn: '',
        showCharCount: false,
        showWordCount: false,
        addons: [],
        inputType: 'tel',
        inputMode: 'decimal',
        id: 'emofhsq',
        defaultValue: '',
        inputMaskPlaceholderChar: '',
      },
    ],
    tableView: false,
    label: 'Page 1',
    id: 'ethn46j',
    type: 'panel',
    title: 'Primary Investor',
    key: 'page1',
    placeholder: '',
    prefix: '',
    customClass: '',
    suffix: '',
    multiple: false,
    defaultValue: null,
    protected: false,
    unique: false,
    persistent: false,
    hidden: false,
    clearOnHide: false,
    refreshOn: '',
    redrawOn: '',
    modalEdit: false,
    dataGridLabel: false,
    labelPosition: 'top',
    description: '',
    errorLabel: '',
    tooltip: '',
    hideLabel: false,
    tabindex: '',
    disabled: false,
    autofocus: false,
    dbIndex: false,
    customDefaultValue: '',
    calculateValue: '',
    calculateServer: false,
    widget: null,
    attributes: {},
    validateOn: 'change',
    validate: {
      required: false,
      custom: '',
      customPrivate: false,
      strictDateValidation: false,
      multiple: false,
      unique: false,
    },
    conditional: {
      show: null,
      when: null,
      eq: '',
    },
    overlay: {
      style: '',
      left: '',
      top: '',
      width: '',
      height: '',
    },
    allowCalculateOverride: false,
    encrypted: false,
    showCharCount: false,
    showWordCount: false,
    properties: {},
    allowMultipleMasks: false,
    tree: false,
    theme: 'default',
    breadcrumb: 'default',
    addons: [],
    lazyLoad: false,
  },
  {
    title: 'Address Info',
    theme: 'default',
    breadcrumb: 'default',
    breadcrumbClickable: true,
    buttonSettings: {
      previous: true,
      cancel: true,
      next: true,
    },
    navigateOnEnter: false,
    saveOnEnter: false,
    scrollToTop: false,
    tooltip: '',
    customClass: '',
    collapsible: false,
    hidden: false,
    hideLabel: false,
    disabled: false,
    modalEdit: false,
    key: 'page3',
    tags: [],
    properties: {},
    conditional: {
      show: null,
      when: null,
      eq: '',
      json: '',
    },
    customConditional: '',
    nextPage: '',
    logic: [],
    attributes: {},
    overlay: {
      style: '',
      page: '',
      left: '',
      top: '',
      width: '',
      height: '',
    },
    type: 'panel',
    label: 'Page 3',
    tabindex: '',
    dataGridLabel: false,
    input: false,
    tableView: false,
    components: [
      {
        label: 'Addresses',
        labelPosition: 'top',
        description: '',
        tooltip: '',
        disableAddingRemovingRows: false,
        conditionalAddButton: '',
        reorder: false,
        addAnother: '',
        addAnotherPosition: 'bottom',
        layoutFixed: false,
        enableRowGroups: false,
        initEmpty: false,
        customClass: '',
        tabindex: '',
        hidden: false,
        hideLabel: false,
        autofocus: false,
        disabled: false,
        tableView: false,
        modalEdit: false,
        defaultValue: [
          {
            address1: '',
            address2: '',
            city: '',
            state: '',
            zipCode: '',
          },
        ],
        persistent: true,
        protected: false,
        dbIndex: false,
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          minLength: '',
          maxLength: '',
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        validateWhenHidden: false,
        errorLabel: '',
        errors: '',
        key: 'addresses',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'datagrid',
        dataGridLabel: false,
        input: true,
        components: [
          {
            label: 'Columns',
            columns: [
              {
                components: [
                  {
                    label: 'Address Line 1',
                    applyMaskOn: 'change',
                    tableView: true,
                    validate: {
                      required: true,
                      custom: '',
                      customPrivate: false,
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                      minLength: '',
                      maxLength: '',
                      pattern: '',
                    },
                    validateWhenHidden: false,
                    key: 'address1',
                    type: 'textfield',
                    input: true,
                    id: 'eyzp5qf',
                    placeholder: '',
                    prefix: '',
                    customClass: '',
                    suffix: '',
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: true,
                    hidden: false,
                    clearOnHide: true,
                    refreshOn: '',
                    redrawOn: '',
                    modalEdit: false,
                    dataGridLabel: false,
                    labelPosition: 'top',
                    description: '',
                    errorLabel: '',
                    tooltip: '',
                    hideLabel: false,
                    tabindex: '',
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    widget: {
                      type: 'input',
                    },
                    attributes: {},
                    validateOn: 'change',
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                    },
                    overlay: {
                      style: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputFormat: 'plain',
                    inputMask: '',
                    displayMask: '',
                    spellcheck: true,
                    truncateMultipleSpaces: false,
                  },
                ],
                width: 6,
                offset: 0,
                push: 0,
                pull: 0,
                size: 'md',
                currentWidth: 6,
              },
              {
                components: [
                  {
                    label: 'Address Line 2',
                    applyMaskOn: 'change',
                    tableView: true,
                    validateWhenHidden: false,
                    key: 'address2',
                    type: 'textfield',
                    input: true,
                    id: 'evwzvyo',
                    placeholder: '',
                    prefix: '',
                    customClass: '',
                    suffix: '',
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: true,
                    hidden: false,
                    clearOnHide: true,
                    refreshOn: '',
                    redrawOn: '',
                    modalEdit: false,
                    dataGridLabel: false,
                    labelPosition: 'top',
                    description: '',
                    errorLabel: '',
                    tooltip: '',
                    hideLabel: false,
                    tabindex: '',
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    widget: {
                      type: 'input',
                    },
                    attributes: {},
                    validateOn: 'change',
                    validate: {
                      required: false,
                      custom: '',
                      customPrivate: false,
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                      minLength: '',
                      maxLength: '',
                      pattern: '',
                    },
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                    },
                    overlay: {
                      style: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputFormat: 'plain',
                    inputMask: '',
                    displayMask: '',
                    spellcheck: true,
                    truncateMultipleSpaces: false,
                  },
                ],
                width: 6,
                offset: 0,
                push: 0,
                pull: 0,
                size: 'md',
                currentWidth: 6,
              },
            ],
            key: 'columns',
            type: 'columns',
            input: false,
            tableView: false,
            id: 'esmo0nf',
            placeholder: '',
            prefix: '',
            customClass: '',
            suffix: '',
            multiple: false,
            defaultValue: null,
            protected: false,
            unique: false,
            persistent: false,
            hidden: false,
            clearOnHide: false,
            refreshOn: '',
            redrawOn: '',
            modalEdit: false,
            dataGridLabel: false,
            labelPosition: 'top',
            description: '',
            errorLabel: '',
            tooltip: '',
            hideLabel: false,
            tabindex: '',
            disabled: false,
            autofocus: false,
            dbIndex: false,
            customDefaultValue: '',
            calculateValue: '',
            calculateServer: false,
            widget: null,
            attributes: {},
            validateOn: 'change',
            validate: {
              required: false,
              custom: '',
              customPrivate: false,
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            conditional: {
              show: null,
              when: null,
              eq: '',
            },
            overlay: {
              style: '',
              left: '',
              top: '',
              width: '',
              height: '',
            },
            allowCalculateOverride: false,
            encrypted: false,
            showCharCount: false,
            showWordCount: false,
            properties: {},
            allowMultipleMasks: false,
            addons: [],
            tree: false,
            lazyLoad: false,
            autoAdjust: false,
          },
          {
            label: 'Columns',
            columns: [
              {
                components: [
                  {
                    label: 'City',
                    applyMaskOn: 'change',
                    tableView: true,
                    validate: {
                      required: true,
                      custom: '',
                      customPrivate: false,
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                      minLength: '',
                      maxLength: '',
                      pattern: '',
                    },
                    validateWhenHidden: false,
                    key: 'city',
                    type: 'textfield',
                    input: true,
                    id: 'e53chv7',
                    placeholder: '',
                    prefix: '',
                    customClass: '',
                    suffix: '',
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: true,
                    hidden: false,
                    clearOnHide: true,
                    refreshOn: '',
                    redrawOn: '',
                    modalEdit: false,
                    dataGridLabel: false,
                    labelPosition: 'top',
                    description: '',
                    errorLabel: '',
                    tooltip: '',
                    hideLabel: false,
                    tabindex: '',
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    widget: {
                      type: 'input',
                    },
                    attributes: {},
                    validateOn: 'change',
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                    },
                    overlay: {
                      style: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputFormat: 'plain',
                    inputMask: '',
                    displayMask: '',
                    spellcheck: true,
                    truncateMultipleSpaces: false,
                  },
                ],
                width: 4,
                offset: 0,
                push: 0,
                pull: 0,
                size: 'md',
                currentWidth: 4,
              },
              {
                components: [
                  {
                    data: {
                      values: [
                        {
                          label: '',
                          value: 'AL',
                        },
                        {
                          label: '',
                          value: 'AK',
                        },
                        {
                          label: '',
                          value: 'AZ',
                        },
                        {
                          label: '',
                          value: 'AR',
                        },
                        {
                          label: '',
                          value: 'CA',
                        },
                        {
                          label: '',
                          value: 'CO',
                        },
                        {
                          label: '',
                          value: 'CT',
                        },
                        {
                          label: '',
                          value: 'DE',
                        },
                        {
                          label: '',
                          value: 'DC',
                        },
                        {
                          label: '',
                          value: 'FL',
                        },
                        {
                          label: '',
                          value: 'GA',
                        },
                        {
                          label: '',
                          value: 'HI',
                        },
                        {
                          label: '',
                          value: 'ID',
                        },
                        {
                          label: '',
                          value: 'IL',
                        },
                        {
                          label: '',
                          value: 'IN',
                        },
                        {
                          label: '',
                          value: 'IA',
                        },
                        {
                          label: '',
                          value: 'KS',
                        },
                        {
                          label: '',
                          value: 'KY',
                        },
                        {
                          label: '',
                          value: 'LA',
                        },
                        {
                          label: '',
                          value: 'ME',
                        },
                        {
                          label: '',
                          value: 'MD',
                        },
                        {
                          label: '',
                          value: 'MA',
                        },
                        {
                          label: '',
                          value: 'MI',
                        },
                        {
                          label: '',
                          value: 'MN',
                        },
                        {
                          label: '',
                          value: 'MS',
                        },
                        {
                          label: '',
                          value: 'MO',
                        },
                        {
                          label: '',
                          value: 'MT',
                        },
                        {
                          label: '',
                          value: 'NE',
                        },
                        {
                          label: '',
                          value: 'NV',
                        },
                        {
                          label: '',
                          value: 'NH',
                        },
                        {
                          label: '',
                          value: 'NJ',
                        },
                        {
                          label: '',
                          value: 'NM',
                        },
                        {
                          label: '',
                          value: 'NY',
                        },
                        {
                          label: '',
                          value: 'NC',
                        },
                        {
                          label: '',
                          value: 'ND',
                        },
                        {
                          label: '',
                          value: 'OH',
                        },
                        {
                          label: '',
                          value: 'OK',
                        },
                        {
                          label: '',
                          value: 'OR',
                        },
                        {
                          label: '',
                          value: 'PA',
                        },
                        {
                          label: '',
                          value: 'RI',
                        },
                        {
                          label: '',
                          value: 'SC',
                        },
                        {
                          label: '',
                          value: 'SD',
                        },
                        {
                          label: '',
                          value: 'TN',
                        },
                        {
                          label: '',
                          value: 'TX',
                        },
                        {
                          label: '',
                          value: 'UT',
                        },
                        {
                          label: '',
                          value: 'VT',
                        },
                        {
                          label: '',
                          value: 'VA',
                        },
                        {
                          label: '',
                          value: 'WA',
                        },
                        {
                          label: '',
                          value: 'WV',
                        },
                        {
                          label: '',
                          value: 'WI',
                        },
                        {
                          label: '',
                          value: 'WY',
                        },
                      ],
                      json: '',
                      url: '',
                      resource: '',
                      custom: '',
                    },
                    input: true,
                    key: 'state',
                    label: 'State',
                    tableView: true,
                    template: '<span>{{ item.value }}</span>',
                    type: 'select',
                    validate: {
                      required: true,
                      custom: '',
                      customPrivate: false,
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                      onlyAvailableItems: false,
                    },
                    widget: 'choicesjs',
                    id: 'ezstzo7',
                    placeholder: '',
                    prefix: '',
                    customClass: '',
                    suffix: '',
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: true,
                    hidden: false,
                    clearOnHide: true,
                    refreshOn: '',
                    redrawOn: '',
                    modalEdit: false,
                    dataGridLabel: false,
                    labelPosition: 'top',
                    description: '',
                    errorLabel: '',
                    tooltip: '',
                    hideLabel: false,
                    tabindex: '',
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    attributes: {},
                    validateOn: 'change',
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                    },
                    overlay: {
                      style: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    dataSrc: 'values',
                    authenticate: false,
                    ignoreCache: false,
                    idPath: 'id',
                    clearOnRefresh: false,
                    limit: 100,
                    valueProperty: '',
                    lazyLoad: true,
                    filter: '',
                    searchEnabled: true,
                    searchDebounce: 0.3,
                    searchField: '',
                    minSearch: 0,
                    readOnlyValue: false,
                    selectFields: '',
                    selectThreshold: 0.3,
                    uniqueOptions: false,
                    fuseOptions: {
                      include: 'score',
                      threshold: 0.3,
                    },
                    indexeddb: {
                      filter: {},
                    },
                    customOptions: {},
                    useExactSearch: false,
                  },
                ],
                width: 4,
                offset: 0,
                push: 0,
                pull: 0,
                size: 'md',
                currentWidth: 4,
              },
              {
                components: [
                  {
                    label: 'Zip Code',
                    applyMaskOn: 'change',
                    tableView: true,
                    validate: {
                      required: true,
                      custom: '',
                      customPrivate: false,
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                      minLength: '',
                      maxLength: '',
                      pattern: '',
                    },
                    validateWhenHidden: false,
                    key: 'zipCode',
                    type: 'textfield',
                    input: true,
                    id: 'e3r1e14',
                    placeholder: '',
                    prefix: '',
                    customClass: '',
                    suffix: '',
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: true,
                    hidden: false,
                    clearOnHide: true,
                    refreshOn: '',
                    redrawOn: '',
                    modalEdit: false,
                    dataGridLabel: false,
                    labelPosition: 'top',
                    description: '',
                    errorLabel: '',
                    tooltip: '',
                    hideLabel: false,
                    tabindex: '',
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    widget: {
                      type: 'input',
                    },
                    attributes: {},
                    validateOn: 'change',
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                    },
                    overlay: {
                      style: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputFormat: 'plain',
                    inputMask: '',
                    displayMask: '',
                    spellcheck: true,
                    truncateMultipleSpaces: false,
                  },
                ],
                size: 'md',
                width: 4,
                currentWidth: 4,
              },
            ],
            key: 'columns1',
            type: 'columns',
            input: false,
            tableView: false,
            id: 'erm7x95',
            placeholder: '',
            prefix: '',
            customClass: '',
            suffix: '',
            multiple: false,
            defaultValue: null,
            protected: false,
            unique: false,
            persistent: false,
            hidden: false,
            clearOnHide: false,
            refreshOn: '',
            redrawOn: '',
            modalEdit: false,
            dataGridLabel: false,
            labelPosition: 'top',
            description: '',
            errorLabel: '',
            tooltip: '',
            hideLabel: false,
            tabindex: '',
            disabled: false,
            autofocus: false,
            dbIndex: false,
            customDefaultValue: '',
            calculateValue: '',
            calculateServer: false,
            widget: null,
            attributes: {},
            validateOn: 'change',
            validate: {
              required: false,
              custom: '',
              customPrivate: false,
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            conditional: {
              show: null,
              when: null,
              eq: '',
            },
            overlay: {
              style: '',
              left: '',
              top: '',
              width: '',
              height: '',
            },
            allowCalculateOverride: false,
            encrypted: false,
            showCharCount: false,
            showWordCount: false,
            properties: {},
            allowMultipleMasks: false,
            addons: [],
            tree: false,
            lazyLoad: false,
            autoAdjust: false,
          },
          {
            label: 'Columns',
            columns: [
              {
                components: [
                  {
                    label: 'Type',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    data: {
                      values: [
                        {
                          label: 'Home',
                          value: 'home',
                        },
                        {
                          label: 'Work',
                          value: 'work',
                        },
                        {
                          label: 'Mobile',
                          value: 'mobile',
                        },
                        {
                          label: 'Vacation',
                          value: 'vacation',
                        },
                        {
                          label: 'Fax',
                          value: 'fax',
                        },
                        {
                          label: 'Other',
                          value: 'other',
                        },
                      ],
                      resource: '',
                      url: '',
                      json: '',
                      custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                      required: false,
                      onlyAvailableItems: false,
                      customMessage: '',
                      custom: '',
                      customPrivate: false,
                      json: '',
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                    },
                    unique: false,
                    validateWhenHidden: false,
                    errorLabel: '',
                    errors: '',
                    key: 'type',
                    tags: [],
                    properties: {},
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                      json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                      style: '',
                      page: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    type: 'select',
                    indexeddb: {
                      filter: {},
                    },
                    dataGridLabel: false,
                    lazyLoad: true,
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    authenticate: false,
                    ignoreCache: false,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    fuseOptions: {
                      include: 'score',
                      threshold: 0.3,
                    },
                    id: 'enlwk0p',
                    defaultValue: 'home',
                  },
                ],
                width: 6,
                offset: 0,
                push: 0,
                pull: 0,
                size: 'md',
                currentWidth: 6,
              },
              {
                components: [
                  {
                    label: 'Is Mailing Address',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: true,
                    data: {
                      values: [
                        {
                          label: 'Yes',
                          value: 'true',
                        },
                        {
                          label: 'No',
                          value: 'false',
                        },
                      ],
                      resource: '',
                      url: '',
                      json: '',
                      custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                      required: false,
                      onlyAvailableItems: false,
                      customMessage: '',
                      custom: '',
                      customPrivate: false,
                      json: '',
                      strictDateValidation: false,
                      multiple: false,
                      unique: false,
                    },
                    unique: false,
                    validateWhenHidden: false,
                    errorLabel: '',
                    errors: '',
                    key: 'isMailingAddress',
                    tags: [],
                    properties: {},
                    conditional: {
                      show: null,
                      when: null,
                      eq: '',
                      json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                      style: '',
                      page: '',
                      left: '',
                      top: '',
                      width: '',
                      height: '',
                    },
                    type: 'select',
                    indexeddb: {
                      filter: {},
                    },
                    dataGridLabel: false,
                    lazyLoad: true,
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    authenticate: false,
                    ignoreCache: false,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    fuseOptions: {
                      include: 'score',
                      threshold: 0.3,
                    },
                    id: 'ei0cs9',
                  },
                ],
                width: 6,
                offset: 0,
                push: 0,
                pull: 0,
                size: 'md',
                currentWidth: 6,
              },
            ],
            key: 'columns2',
            type: 'columns',
            input: false,
            tableView: false,
            id: 'e4z3ohm',
            placeholder: '',
            prefix: '',
            customClass: '',
            suffix: '',
            multiple: false,
            defaultValue: null,
            protected: false,
            unique: false,
            persistent: false,
            hidden: false,
            clearOnHide: false,
            refreshOn: '',
            redrawOn: '',
            modalEdit: false,
            dataGridLabel: false,
            labelPosition: 'top',
            description: '',
            errorLabel: '',
            tooltip: '',
            hideLabel: false,
            tabindex: '',
            disabled: false,
            autofocus: false,
            dbIndex: false,
            customDefaultValue: '',
            calculateValue: '',
            calculateServer: false,
            widget: null,
            attributes: {},
            validateOn: 'change',
            validate: {
              required: false,
              custom: '',
              customPrivate: false,
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            conditional: {
              show: null,
              when: null,
              eq: '',
            },
            overlay: {
              style: '',
              left: '',
              top: '',
              width: '',
              height: '',
            },
            allowCalculateOverride: false,
            encrypted: false,
            showCharCount: false,
            showWordCount: false,
            properties: {},
            allowMultipleMasks: false,
            addons: [],
            tree: false,
            lazyLoad: false,
            autoAdjust: false,
          },
        ],
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        unique: false,
        refreshOn: '',
        widget: null,
        showCharCount: false,
        showWordCount: false,
        allowMultipleMasks: false,
        addons: [],
        tree: true,
        lazyLoad: false,
        id: 'egitkbr',
      },
    ],
    placeholder: '',
    prefix: '',
    suffix: '',
    multiple: false,
    defaultValue: null,
    protected: false,
    unique: false,
    persistent: false,
    clearOnHide: false,
    refreshOn: '',
    redrawOn: '',
    labelPosition: 'top',
    description: '',
    errorLabel: '',
    autofocus: false,
    dbIndex: false,
    customDefaultValue: '',
    calculateValue: '',
    calculateServer: false,
    widget: null,
    validateOn: 'change',
    validate: {
      required: false,
      custom: '',
      customPrivate: false,
      strictDateValidation: false,
      multiple: false,
      unique: false,
    },
    allowCalculateOverride: false,
    encrypted: false,
    showCharCount: false,
    showWordCount: false,
    allowMultipleMasks: false,
    addons: [],
    tree: false,
    lazyLoad: false,
    id: 'eseoeh8',
  },
  {
    input: false,
    components: [
      {
        label: 'Include a Joint Investor?',
        labelPosition: 'top',
        widget: 'choicesjs',
        placeholder: '',
        description: '',
        tooltip: '',
        customClass: '',
        tabindex: '',
        hidden: false,
        hideLabel: false,
        uniqueOptions: false,
        autofocus: false,
        disabled: false,
        tableView: true,
        modalEdit: false,
        multiple: false,
        dataSrc: 'values',
        data: {
          values: [
            {
              value: 'true',
              label: 'Yes',
            },
            {
              value: 'false',
              label: 'No',
            },
          ],
          resource: '',
          url: '',
          json: '',
          custom: '',
        },
        dataType: '',
        idPath: 'id',
        valueProperty: '',
        template: '<span>{{ item.label }}</span>',
        refreshOn: '',
        refreshOnBlur: '',
        clearOnRefresh: false,
        searchEnabled: true,
        selectThreshold: 0.3,
        readOnlyValue: false,
        customOptions: {},
        useExactSearch: false,
        persistent: true,
        protected: false,
        dbIndex: false,
        encrypted: false,
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: true,
          onlyAvailableItems: false,
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        validateWhenHidden: false,
        errorLabel: '',
        errors: '',
        key: 'includeSecondInvestor',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'select',
        indexeddb: {
          filter: {},
        },
        dataGridLabel: false,
        lazyLoad: true,
        selectFields: '',
        searchField: '',
        searchDebounce: 0.3,
        minSearch: 0,
        filter: '',
        limit: 100,
        authenticate: false,
        ignoreCache: false,
        redrawOn: '',
        input: true,
        prefix: '',
        suffix: '',
        showCharCount: false,
        showWordCount: false,
        allowMultipleMasks: false,
        addons: [],
        fuseOptions: {
          include: 'score',
          threshold: 0.3,
        },
        id: 'e0dnpla',
        defaultValue: false,
      },
      {
        allowMultipleMasks: false,
        redrawOn: '',
        conditional: {
          show: true,
          json: '',
          eq: 'true',
          when: 'includeSecondInvestor',
        },
        prefix: '',
        defaultValue: '',
        tooltip: '',
        suffix: '',
        type: 'textfield',
        calculateValue: '',
        protected: false,
        dbIndex: false,
        modalEdit: false,
        inputType: 'text',
        id: 'ellmi2r',
        persistent: true,
        case: '',
        hideLabel: false,
        customConditional: '',
        overlay: {
          width: '',
          style: '',
          page: '',
          top: '',
          left: '',
          height: '',
        },
        tabindex: '',
        clearOnHide: true,
        inputFormat: 'plain',
        tags: [],
        input: true,
        customDefaultValue: '',
        spellcheck: true,
        unique: false,
        showCharCount: false,
        errorLabel: '',
        widget: {
          type: 'input',
        },
        refreshOn: '',
        hidden: false,
        description: '',
        labelPosition: 'top',
        calculateServer: false,
        disabled: false,
        placeholder: '',
        key: 'secondInvestor.firstName',
        mask: false,
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          minLength: '',
          unique: false,
          pattern: '',
          multiple: false,
          customMessage: '',
          json: '',
          required: true,
          maxLength: '',
        },
        autocomplete: '',
        allowCalculateOverride: false,
        dataGridLabel: false,
        multiple: false,
        tableView: true,
        label: 'First Name',
        inputMask: '',
        autofocus: false,
        showWordCount: false,
        validateOn: 'change',
        encrypted: false,
        customClass: '',
        attributes: {},
        logic: [],
        properties: {},
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        redrawOn: '',
        allowMultipleMasks: false,
        conditional: {
          show: true,
          json: '',
          eq: 'true',
          when: 'includeSecondInvestor',
        },
        prefix: '',
        defaultValue: null,
        tooltip: '',
        type: 'textfield',
        suffix: '',
        calculateValue: '',
        protected: false,
        dbIndex: false,
        modalEdit: false,
        inputType: 'text',
        id: 'e9p0qn',
        persistent: true,
        hideLabel: false,
        overlay: {
          width: '',
          style: '',
          top: '',
          left: '',
          height: '',
        },
        tabindex: '',
        clearOnHide: true,
        inputFormat: 'plain',
        input: true,
        customDefaultValue: '',
        spellcheck: true,
        unique: false,
        showCharCount: false,
        errorLabel: '',
        refreshOn: '',
        widget: {
          type: 'input',
        },
        hidden: false,
        description: '',
        labelPosition: 'top',
        calculateServer: false,
        disabled: false,
        placeholder: '',
        key: 'secondInvestor.middleInitial',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          unique: false,
          minLength: '',
          multiple: false,
          pattern: '',
          required: false,
          maxLength: '',
        },
        mask: false,
        dataGridLabel: false,
        allowCalculateOverride: false,
        multiple: false,
        tableView: true,
        label: 'Middle Initial',
        autofocus: false,
        inputMask: '',
        showWordCount: false,
        validateOn: 'change',
        encrypted: false,
        customClass: '',
        attributes: {},
        properties: {},
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        redrawOn: '',
        allowMultipleMasks: false,
        conditional: {
          show: true,
          json: '',
          eq: 'true',
          when: 'includeSecondInvestor',
        },
        prefix: '',
        defaultValue: null,
        tooltip: '',
        type: 'textfield',
        suffix: '',
        calculateValue: '',
        protected: false,
        dbIndex: false,
        modalEdit: false,
        inputType: 'text',
        id: 'e9kowvd',
        persistent: true,
        hideLabel: false,
        overlay: {
          width: '',
          style: '',
          top: '',
          left: '',
          height: '',
        },
        tabindex: '',
        clearOnHide: true,
        inputFormat: 'plain',
        input: true,
        customDefaultValue: '',
        spellcheck: true,
        unique: false,
        showCharCount: false,
        errorLabel: '',
        refreshOn: '',
        widget: {
          type: 'input',
        },
        hidden: false,
        description: '',
        labelPosition: 'top',
        calculateServer: false,
        disabled: false,
        placeholder: '',
        key: 'secondInvestor.lastName',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          unique: false,
          minLength: '',
          multiple: false,
          pattern: '',
          required: true,
          maxLength: '',
        },
        mask: false,
        dataGridLabel: false,
        allowCalculateOverride: false,
        multiple: false,
        tableView: true,
        label: 'Last Name',
        autofocus: false,
        inputMask: '',
        showWordCount: false,
        validateOn: 'change',
        encrypted: false,
        customClass: '',
        attributes: {},
        properties: {},
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        redrawOn: '',
        allowMultipleMasks: false,
        conditional: {
          show: true,
          json: '',
          eq: 'true',
          when: 'includeSecondInvestor',
        },
        prefix: '',
        defaultValue: null,
        tooltip: '',
        type: 'email',
        suffix: '',
        calculateValue: '',
        protected: false,
        dbIndex: false,
        modalEdit: false,
        inputType: 'email',
        id: 'eeyezqe',
        persistent: true,
        hideLabel: false,
        overlay: {
          width: '',
          style: '',
          top: '',
          left: '',
          height: '',
        },
        tabindex: '',
        clearOnHide: true,
        inputFormat: 'plain',
        input: true,
        customDefaultValue: '',
        spellcheck: true,
        unique: false,
        showCharCount: false,
        errorLabel: '',
        refreshOn: '',
        widget: {
          type: 'input',
        },
        hidden: false,
        description: '',
        kickbox: {
          enabled: false,
        },
        labelPosition: 'top',
        calculateServer: false,
        disabled: false,
        placeholder: '',
        key: 'secondInvestor.email',
        validate: {
          strictDateValidation: false,
          custom: '',
          customPrivate: false,
          unique: false,
          minLength: '',
          multiple: false,
          pattern: '',
          required: true,
          maxLength: '',
        },
        mask: false,
        dataGridLabel: false,
        allowCalculateOverride: false,
        multiple: false,
        tableView: true,
        label: 'Email',
        autofocus: false,
        inputMask: '',
        showWordCount: false,
        validateOn: 'change',
        encrypted: false,
        customClass: '',
        attributes: {},
        properties: {},
        addons: [],
        displayMask: '',
        truncateMultipleSpaces: false,
      },
      {
        label: 'Phone Number',
        labelPosition: 'top',
        placeholder: '',
        description: '',
        tooltip: '',
        prefix: '',
        suffix: '',
        widget: {
          type: 'input',
        },
        inputMask: '',
        displayMask: '(999) 999-9999',
        applyMaskOn: 'change',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        mask: false,
        autofocus: false,
        spellcheck: false,
        disabled: false,
        tableView: false,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        truncateMultipleSpaces: false,
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: true,
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
          minLength: '',
          maxLength: '',
          pattern: '',
        },
        unique: false,
        validateWhenHidden: false,
        errorLabel: '',
        errors: '',
        key: 'secondInvestor.phoneNumber',
        tags: [],
        properties: {},
        conditional: {
          show: true,
          when: 'includeSecondInvestor',
          eq: 'true',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'phoneNumber',
        dataGridLabel: false,
        input: true,
        refreshOn: '',
        showCharCount: false,
        showWordCount: false,
        addons: [],
        inputType: 'tel',
        inputMode: 'decimal',
        id: 'er0s8f',
        defaultValue: '',
        inputMaskPlaceholderChar: '',
      },
    ],
    tableView: false,
    label: 'Page 2',
    id: 'evocw5',
    type: 'panel',
    title: 'Joint Investor',
    key: 'page2',
    placeholder: '',
    prefix: '',
    customClass: '',
    suffix: '',
    multiple: false,
    defaultValue: null,
    protected: false,
    unique: false,
    persistent: false,
    hidden: false,
    clearOnHide: false,
    refreshOn: '',
    redrawOn: '',
    modalEdit: false,
    dataGridLabel: false,
    labelPosition: 'top',
    description: '',
    errorLabel: '',
    tooltip: '',
    hideLabel: false,
    tabindex: '',
    disabled: false,
    autofocus: false,
    dbIndex: false,
    customDefaultValue: '',
    calculateValue: '',
    calculateServer: false,
    widget: null,
    attributes: {},
    validateOn: 'change',
    validate: {
      required: false,
      custom: '',
      customPrivate: false,
      strictDateValidation: false,
      multiple: false,
      unique: false,
    },
    conditional: {
      show: null,
      when: null,
      eq: '',
    },
    overlay: {
      style: '',
      left: '',
      top: '',
      width: '',
      height: '',
    },
    allowCalculateOverride: false,
    encrypted: false,
    showCharCount: false,
    showWordCount: false,
    properties: {},
    allowMultipleMasks: false,
    addons: [],
    tree: false,
    lazyLoad: false,
    theme: 'default',
    breadcrumb: 'default',
  },
];
