import { Platform } from './_@types';

export const PLATFORMS: Platform[] = [
  {
    name: 'Absolute Capital',
    logo: '/logo/platforms/absolute-capital.jpg',
    models: [
      { id: '31839', name: 'Asset Allocator Aggressive Growth' },
      { id: '31828', name: 'Asset Allocator Growth' },
      { id: '31830', name: 'Asset Allocator Core' },
      { id: '31833', name: 'Asset Allocator Conservative' },
      { id: '31837', name: 'Asset Allocator Income' },
      { id: '23424', name: 'Portfolio Protector High-Yield' },
      { id: '23425', name: 'Portfolio Protector Multi-Fund' },
    ],
  },
  {
    name: 'Advanced Asset Management Advisors',
    logo: '/logo/platforms/aama.jpg',
    models: [
      { id: '12085', name: 'Aggressive Growth' },
      { id: '12079', name: 'Growth' },
      { id: '12087', name: 'Strategic Balanced' },
      { id: '12083', name: 'Global Aggressive Growth' },
      { id: '12080', name: 'Global Growth' },
      { id: '12081', name: 'Global Strategic Balanced' },
    ],
  },
  {
    name: 'American Funds',
    logo: '/logo/platforms/american-funds.jpg',
    models: [
      { id: '78000', name: 'Conservative Growth & Income' },
      { id: '78003', name: 'Conservative Income' },
      { id: '78004', name: 'Global Growth' },
      { id: '78007', name: 'Growth & Income' },
      { id: '78005', name: 'Growth' },
      { id: '78009', name: 'Moderate Growth & Income' },
      { id: '78008', name: 'Moderate Growth' },
      { id: '78010', name: 'Preservation' },
      { id: '78011', name: 'Retirement Income - Conservative' },
      { id: '78012', name: 'Retirement Income - Enhanced' },
      { id: '78013', name: 'Retirement Income - Moderate' },
    ],
  },
  {
    name: 'BlackRock',
    logo: '/logo/platforms/blackrock.png',
    models: [
      { id: '51830', name: 'Strategic ETF 60/40' },
      { id: '51833', name: 'Strategic ETF 80/20' },
      { id: '51834', name: 'Strategic ETF 100/0' },
      { id: '51838', name: 'Target Income Core Income' },
      { id: '51839', name: 'Target Income Moderate Income' },
      { id: '51840', name: 'Target Income High Income' },
      { id: '51841', name: 'Target Income Aggressive Income' },
      { id: '84698', name: 'Multi Asset Income Conservative' },
      { id: '84700', name: 'Multi Asset Income Moderate' },
      { id: '84702', name: 'Multi Asset Income Growth' },
    ],
  },
  {
    name: 'Frontier Asset Management',
    logo: '/logo/platforms/frontier-asset.png',
    models: [
      { id: '23328', name: 'Absolute Return' },
      { id: '23333', name: 'Absolute Return Plus' },
      { id: '27764', name: 'Balanced' },
      { id: '23334', name: 'Focused Opportunities' },
      { id: '27760', name: 'Global Opportunities' },
      { id: '27765', name: 'Conservative Multi-Asset Income' },
      { id: '27762', name: 'Long Term Growth' },
    ],
  },
  {
    name: 'GWN Select',
    logo: '/logo/platforms/gwn-select.jpg',
    models: [
      { id: '12099', name: 'Maximum Appreciation' },
      { id: '12059', name: 'Growth Appreciation' },
      { id: '12089', name: 'Moderate' },
      { id: '12098', name: 'Balanced' },
      { id: '12095', name: 'Conservative' },
    ],
  },
  {
    name: 'Castellum Asset Management',
    logo: '/logo/platforms/gwn-select-etf.jpg',
    models: [
      { id: '27461', name: 'Dynamic ETF Balanced' },
      { id: '27467', name: 'Dynamic ETF Conservative' },
      { id: '11989', name: 'Flexible Strategy ETF' },
      { id: '27462', name: 'Dynamic ETF Growth Appreciation' },
      { id: '27464', name: 'Dynamic ETF Maximum Appreciation' },
      { id: '27468', name: 'Dynamic ETF Moderate' },
      { id: '23045', name: 'Strategic ETF Balanced' },
      { id: '23044', name: 'Strategic ETF Conservative' },
      { id: '23049', name: 'Strategic ETF Growth Appreciation' },
      { id: '23051', name: 'Strategic ETF Maximum Appreciation' },
      { id: '23046', name: 'Strategic ETF Moderate' },
      // Castellum Strategic Single Fund Family
      { id: '67508', name: 'American Funds Aggressive' },
      { id: '67099', name: 'American Funds Balanced' },
      { id: '67511', name: 'American Funds Conservative' },
      { id: '66978', name: 'American Funds Growth' },
      { id: '57655', name: 'American Funds Moderate' },
      { id: '47353', name: 'Vanguard Aggressive' },
      { id: '46657', name: 'Vanguard Balanced' },
      { id: '45671', name: 'Vanguard Conservative' },
      { id: '44477', name: 'Vanguard Growth' },
      { id: '44607', name: 'Vanguard Moderate' },
    ],
  },
  {
    name: 'Dimensional',
    logo: '/logo/platforms/dimensional.jpg',
    models: [
      { id: '91980', name: 'Core Plus Wealth 0/100' },
      { id: '92000', name: 'Core Plus Wealth 100/0' },
      { id: '91981', name: 'Core Plus Wealth 20/80' },
      { id: '91983', name: 'Core Plus Wealth 40/60' },
      { id: '91984', name: 'Core Plus Wealth 60/40' },
      { id: '91999', name: 'Core Plus Wealth 80/20' },
      { id: '91964', name: 'Core Wealth 0/100' },
      { id: '91979', name: 'Core Wealth 100/0' },
      { id: '91975', name: 'Core Wealth 20/80' },
      { id: '91976', name: 'Core Wealth 40/60' },
      { id: '91977', name: 'Core Wealth 60/40' },
      { id: '91978', name: 'Core Wealth 80/20' },
    ],
  },
  {
    name: 'Tam Multi-Market',
    logo: '/logo/platforms/tam-multi-market.png',
    models: [
      { id: '100659', name: 'MultiMarket Balanced' },
      { id: '100660', name: 'MultiMarket Balanced Growth' },
      { id: '100661', name: 'MultiMarket Balanced Income' },
    ],
  },
  {
    name: 'Icon',
    logo: '/logo/platforms/icon.png',
    models: [
      { id: '32400', name: 'SBI Global Conservative' },
      { id: '32398', name: 'SBI Global Growth' },
      { id: '32399', name: 'SBI Global Moderate' },
      { id: '12066', name: 'U.S. Growth' },
      { id: '12063', name: 'U.S. Moderate' },
      { id: '22572', name: 'U.S. Income' },
    ],
  },
  {
    name: 'Main Management',
    logo: '/logo/platforms/main-management.jpg',
    models: [
      { id: '82562', name: 'Management BuyWrite' },
      { id: '82563', name: 'Active Sector Rotation ETF' },
    ],
  },
  {
    name: 'Ocean Park Asset Management',
    logo: '/logo/platforms/ocean-park.png',
    models: [
      { id: '11990', name: 'Conservative' },
      { id: '11991', name: 'Tactical Bond' },
    ],
  },
  {
    name: 'Portfolio Strategies Investment Managers',
    logo: '/logo/platforms/portfolio-strategies.jpg',
    models: [{ id: '32293', name: 'Growth Plus' }],
  },
  {
    name: 'Russell Investments',
    logo: '/logo/platforms/russell.png',
    models: [
      { id: '12074', name: 'Core Balanced' },
      { id: '12073', name: 'Core Conservative' },
      { id: '12075', name: 'Core Equity Growth' },
      { id: '12078', name: 'Core Growth' },
      { id: '12101', name: 'Core Moderate' },
    ],
  },
  {
    name: 'Toews',
    logo: '/logo/platforms/toews.png',
    models: [
      { id: '34816', name: 'Fixed Income - Conservative Income' },
      { id: '34817', name: 'Fixed Income - Moderate Income' },
      { id: '34818', name: 'Fixed Income - High Income' },
      { id: '34802', name: 'Hedged Capital Preservation' },
      { id: '34803', name: 'Hedged Balanced Income' },
      { id: '34805', name: 'Hedged Balanced' },
      { id: '34807', name: 'Hedged Balanced Growth' },
      { id: '34814', name: 'Hedged Growth' },
      { id: '34815', name: 'Hedged All Equity' },
      { id: '107225', name: 'Managed Risk Blueprint ETF' },
      { id: '55050', name: 'Defensive Alpha - Equity' },
    ],
  },
  {
    name: 'Vanguard',
    logo: '/logo/platforms/vanguard.jpg',
    models: [
      { id: '80009', name: 'Vanguard Core ETF 100/0 - (% Equity/Fixed)' },
      { id: '80011', name: 'Vanguard Core ETF 80/20 - (% Equity/Fixed)' },
      { id: '80012', name: 'Vanguard Core ETF 60/40 - (% Equity/Fixed)' },
      { id: '80014', name: 'Vanguard Core ETF 40/60 - (% Equity/Fixed)' },
      { id: '80015', name: 'Vanguard Core ETF 20/80 - (% Equity/Fixed)' },
      { id: '80017', name: 'Vanguard Core ETF 0/100 - (% Equity/Fixed)' },
    ],
  },
  {
    name: 'Verity Asset Management',
    logo: '/logo/platforms/verity.png',
    models: [
      { id: '61651', name: 'Opportunistic Income ETF Strategy' },
      { id: '61650', name: 'Conservative Total Return ETF Strategy' },
    ],
  },
  {
    name: 'Donoghue Forlines',
    logo: '/logo/platforms/w-e-donoghue.png',
    models: [
      { id: '23337', name: 'Income' },
      { id: '32510', name: 'Dividend and Yield' },
      { id: '32513', name: 'Growth & Income' },
    ],
  },
];

export const KMC_PLATINUM: Platform[] = [
  {
    name: 'American Funds',
    logo: '/logo/platforms/american-funds.jpg',
    tier: 1,
    models: [
      { name: 'Global Growth', id: '75185' },
      { name: 'Growth', id: '75216' },
      { name: 'Growth and Income', id: '75138' },
      { name: 'Moderate Growth', id: '75184' },
      { name: 'Conservative Growth and Income', id: '75214' },
      { name: 'Moderate Growth and Income', id: '75215' },
      { name: 'Retirement Income - Enhanced', id: '75219' },
      { name: 'Retirement Income - Moderate', id: '75218' },
      { name: 'Retirement Income - Conservative', id: '75217' },
      { name: 'Conservative Income', id: '75220' },
      { name: 'Preservation', id: '75212' },
    ],
  },
  {
    name: 'Castellum',
    logo: '/logo/platforms/castellum.jpg',
    tier: 1,
    models: [
      { name: 'Aggressive Growth - Mutual Fund', id: '5751' },
      { name: 'Moderate Aggressive Growth - Mutual Fund', id: '5752' },
      { name: 'Moderate Growth - Mutual Fund', id: '5753' },
      { name: 'Balanced - Mutual Fund', id: '5754' },
      { name: 'Moderate Conservative Income - Mutual Fund', id: '5755' },
      { name: 'Conservative Income - Mutual Fund', id: '5756' },
      { name: 'Ultra Conservative - Mutual Fund', id: '22445' },
      // dynamic
      { name: 'Dynamic Aggressive Growth - ETF', id: '57744' },
      { name: 'Dynamic Moderate Aggressive Growth - ETF', id: '57742' },
      { name: 'Dynamic Moderate Growth - ETF', id: '57511' },
      { name: 'Dynamic Balanced - ETF', id: '57512' },
      { name: 'Dynamic Moderate Conservative Income - ETF', id: '57740' },
      { name: 'Dynamic Conservative Income - ETF', id: '57739' },
      // strategic
      { name: 'Strategic Aggressive Growth - ETF', id: '58087' },
      { name: 'Strategic Moderate Aggressive Growth - ETF', id: '58086' },
      { name: 'Strategic Moderate Growth - ETF', id: '57970' },
      { name: 'Strategic Balanced - ETF', id: '58082' },
      { name: 'Strategic Moderate Conservative Income - ETF', id: '58081' },
      { name: 'Strategic Conservative Income - ETF', id: '58080' },
      // tactical
      { name: 'Tactical Flexible Strategy - ETF', id: '58079' },
    ],
  },
  {
    name: 'Blacrock',
    tier: 1,
    logo: '/logo/platforms/blackrock.png',
    models: [
      { name: 'Multi-Asset Income Growth', id: '84410' },
      { name: 'Multi-Asset Income Moderate', id: '84409' },
      { name: 'Multi-Asset Income Conservative', id: '84408' },
      { name: 'Strategic ETF Asset Allocation 100/0', id: '57535' },
      { name: 'Strategic ETF Asset Allocation 80/20', id: '57509' },
      { name: 'Strategic ETF Asset Allocation 60/40', id: '57510' },
      { name: 'Target Income ETF Aggressive', id: '57544' },
      { name: 'Target Income ETF High Income', id: '57541' },
      { name: 'Target Income ETF Moderate Income', id: '57537' },
      { name: 'Target Income ETF Core Income', id: '57536' },
    ],
  },
  {
    name: 'Vanguard',
    tier: 1,
    logo: '/logo/platforms/vanguard.jpg',
    models: [
      { name: 'ETF Income 0/100', id: '71100' },
      { name: 'ETF Income 20/80', id: '71099' },
      { name: 'ETF Balanced 40/60', id: '71098' },
      { name: 'ETF Balanced 60/40', id: '71097' },
      { name: 'ETF Growth 80/20', id: '71096' },
      { name: 'ETF Growth 100/0', id: '71095' },
    ],
  },
  {
    name: 'Main Management',
    tier: 1,
    logo: '/logo/platforms/main-management.jpg',
    models: [
      { name: 'BuyWrite Strategy', id: '82519' },
      { name: 'Active Sector ETF', id: '82497' },
    ],
  },
  {
    name: 'TAM Multi Market',
    tier: 1,
    logo: '/logo/platforms/tam-multi-market.png',
    models: [
      { name: 'Balanced', id: '102634' },
      { name: 'Balanced Growth', id: '102635' },
      { name: 'Balanced Income', id: '102636' },
    ],
  },
  {
    name: 'Russell Investments',
    tier: 2,
    logo: '/logo/platforms/russell.png',
    models: [
      { name: 'Equity Growth Model Strategy', id: '20219' },
      { name: 'Growth Model Strategy', id: '20141' },
      { name: 'Balanced Model Strategy', id: '20281' },
      { name: 'Moderate Model Strategy', id: '20360' },
      { name: 'Conservative Model Strategy', id: '20379' },
    ],
  },
  {
    name: 'Icon',
    tier: 2,
    logo: '/logo/platforms/icon.png',
    models: [
      { name: 'ICON U.S. Income Model Portfolio', id: '34055' },
      { name: 'ICON U.S. Moderate Model Portfolio', id: '13624' },
      { name: 'ICON U.S. Growth Model Portfolio', id: '13616' },
      { name: 'ICON SBI Global Conservative Model Portfolio', id: '86875' },
      { name: 'ICON SBI Global Moderate Model Portfolio', id: '86873' },
      { name: 'ICON SBI Global Growth Model Portfolio', id: '86871' },
    ],
  },
  {
    name: 'Absolute Capital',
    tier: 2,
    logo: '/logo/platforms/absolute-capital.jpg',
    models: [
      { name: 'Portfolio Protector Bond', id: '23566' },
      { name: 'Portfolio Protector Multi-Fund', id: '24071' },
      { name: 'Asset Allocator Aggressive Growth', id: '23583' },
      { name: 'Asset Allocator Growth', id: '23582' },
      { name: 'Asset Allocator Core', id: '23581' },
      { name: 'Asset Allocator Conservative', id: '23580' },
      { name: 'Asset Allocator Income', id: '23579' },
    ],
  },
  {
    name: 'Toews',
    logo: '/logo/platforms/toews.png',
    tier: 2,
    models: [
      { name: 'Hedged Growth', id: '35080' },
      { name: 'Hedged Balanced Growth', id: '35073' },
      { name: 'Hedged Balanced', id: '35071' },
      { name: 'Hedged Balanced Income', id: '35074' },
      { name: 'Hedged Capital Preservation', id: '35075' },
      { name: 'Dynamic Fixed Income High Income Portfolio', id: '35078' },
      { name: 'Dynamic Fixed Income Moderate Income Portfolio', id: '35079' },
      { name: 'Dynamic Fixed Income Conservative Income Portfolio', id: '35076' },
      { name: 'Tactical Defensive Alpha Balanced', id: '71130' },
      { name: 'Tactical Defensive Alpha Equity', id: '55997' },
    ],
  },
  {
    name: 'Frontier Asset Management',
    logo: '/logo/platforms/frontier-asset.png',
    tier: 2,
    models: [
      { name: 'Global Opportunities', id: '26794' },
      { name: 'Focused Opportunities', id: '27508' },
      { name: 'Long Term Growth', id: '74837' },
      { name: 'Growth and Income', id: '33764' },
      { name: 'Balanced', id: '74836' },
      { name: 'Absolute Return', id: '27507' },
      { name: 'Absolute Return Plus', id: '27758' },
      { name: 'Income', id: '27661' },
    ],
  },
  {
    name: 'Donoghue Forlines',
    logo: '/logo/platforms/w-e-donoghue.png',
    tier: 2,
    models: [
      { name: 'Power Growth and Income', id: '34733' },
      { name: 'Power Dividend and Yield', id: '35082' },
      { name: 'Power Income', id: '35084' },
    ],
  },
  {
    name: 'Advanced Asset Management Advisors (AAMA)',
    logo: '/logo/platforms/aama.jpg',
    tier: 2,
    models: [
      { name: 'Aggressive Growth Portfolio', id: '35594' },
      { name: 'Global Aggressive Growth Portfolio', id: '35597' },
      { name: 'Global Growth Portfolio', id: '35596' },
      { name: 'Global Strategic Balanced Portfolio', id: '35595' },
      { name: 'Growth Portfolio', id: '35593' },
      { name: 'Strategic Balanced Portfolio', id: '35592' },
    ],
  },
  {
    name: 'Clark Capital Management Group',
    logo: '/logo/platforms/clark-capital.png',
    tier: 2,
    models: [
      { name: 'MultiStrategy 75-25', id: '77499' },
      { name: 'MultiStrategy 50-50', id: '77497' },
      { name: 'MultiStrategy 25-75', id: '77498' },
      { name: 'Navigator Fixed Income Total Return', id: '77496' },
      { name: 'Global Risk Management Growth', id: '99308' },
      { name: 'Navigator Risk Management Moderate', id: '99307' },
      { name: 'Navigator Risk Management Conservative', id: '99306' },
    ],
  },
];

export const HUTTO_DEAN = {
  name: 'Millenium Advisory',
  logo: '/logo/platforms/hutto-dean.png',
  type: 'fund',
  models: [
    { id: '12854', name: 'HDSAM' },
    { id: '31396', name: 'HDSAM GROWTH - MAP Only' },
    { id: '49374', name: 'HDSAM VANGUARD' },
    { id: '50321', name: 'HDSAM AMERICAN FUNDS - F SHARES' },
    { id: '54868', name: 'HDSAM FIDELITY' },
    { id: '52575', name: 'MAG-50' },
  ],
};

export const ALLOWED_ADVISORS = {
  // Allowed advisor ID
  // ghutto@gwnsecurities.com
  HUTTO_DEAN: '2d5f64d4-27b6-4751-9d30-d4a6efd38ed7',
  MICHAEL_ZACKA: 'c464ac74-a1d1-4c4a-abed-f60eeb86c73e',
  // Test firm - test+firmadmin@bitsyadvisor.com
  DEV_TEST: 'a1940c58-d752-4f10-b5fd-f200344f9736',
  CARL_NEITZEL: '49710f42-7c2c-4ad9-bec2-00d7211d6486',
};

export const INDIVIDUAL_FUND_LOGO = '/logo/platforms/individual-fund.png';
